// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/GetFileUploadParameters": {
            "post": {
                "description": "given certain details about an incoming upload, it retrieves information necessary for successfull upload e.g batch size",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetFileUploadParameters API"
                ],
                "summary": "GetFileUploadParameters",
                "parameters": [
                    {
                        "description": "GetFileUploadParametersRequest",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recon_requests.GetFileUploadParametersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GetFileUploadParametersResponse",
                        "schema": {
                            "$ref": "#/definitions/recon_responses.GetFileUploadParametersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/Swagger/index.html": {
            "get": {
                "description": "returns json needed by Swagger",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Swagger APIs"
                ],
                "summary": "Swagger API",
                "responses": {
                    "200": {
                        "description": "Json data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/Swagger/swagger.json": {
            "get": {
                "description": "returns json needed by Swagger",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Swagger APIs"
                ],
                "summary": "GetSwaggerJson",
                "responses": {
                    "200": {
                        "description": "Json data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Entities.ComparisonPair": {
            "type": "object",
            "properties": {
                "comparisonColumnIndex": {
                    "type": "integer"
                },
                "sourceColumnIndex": {
                    "type": "integer"
                }
            }
        },
        "recon_requests.GetFileUploadParametersRequest": {
            "type": "object",
            "required": [
                "comparisionFileName",
                "comparisonFileHash",
                "comparisonPairs",
                "sourceFileHash",
                "sourceFileName",
                "userId"
            ],
            "properties": {
                "comparisionFileName": {
                    "description": "comparison file meta data",
                    "type": "string"
                },
                "comparisonFileHash": {
                    "type": "string"
                },
                "comparisonFileRowCount": {
                    "type": "integer"
                },
                "comparisonPairs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Entities.ComparisonPair"
                    }
                },
                "sourceFileHash": {
                    "type": "string"
                },
                "sourceFileName": {
                    "type": "string"
                },
                "sourceFileRowCount": {
                    "type": "integer"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "recon_responses.GetFileUploadParametersResponse": {
            "type": "object",
            "properties": {
                "comparisonFileExpectedBatchSize": {
                    "type": "integer"
                },
                "comparisonFileHash": {
                    "description": "Comparison File meta",
                    "type": "string"
                },
                "comparisonFileIsFirstTimeUpload": {
                    "description": "flags indicating whether the Comparison file\nis new to us..if not where did we stop",
                    "type": "boolean"
                },
                "comparisonFileLastRowReceived": {
                    "type": "integer"
                },
                "comparisonFileName": {
                    "type": "string"
                },
                "sourceFileExpectedBatchSize": {
                    "type": "integer"
                },
                "sourceFileHash": {
                    "description": "SRC File meta data",
                    "type": "string"
                },
                "sourceFileIsFirstTimeUpload": {
                    "description": "flags indicating whether the SRC file\nis new to us..if not where did we stop",
                    "type": "boolean"
                },
                "sourceFileLastRowReceived": {
                    "type": "integer"
                },
                "sourceFileName": {
                    "type": "string"
                },
                "uploadRequestId": {
                    "description": "unique Id tagged to this whole uplaod",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "us-central1-reconcilercore.cloudfunctions.net",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Reconciler Backend Core API",
	Description: "This is the core backend Reconciler API.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
